apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "coraza-operator.fullname" . }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.istio.io
  resources:
  - wasmplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - serviceentries
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - waf.k8s.coraza.io
  resources:
  - engines
  - rulesets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - waf.k8s.coraza.io
  resources:
  - engines/finalizers
  verbs:
  - update
- apiGroups:
  - waf.k8s.coraza.io
  resources:
  - engines/status
  - rulesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - waf.k8s.coraza.io
  resources:
  - ruledata
  - rulesources
  verbs:
  - get
  - list
  - watch
